services:
  redpanda:
    ports:
      - '127.0.0.1:${REDPANDA_KAFKA_PORT}:19092'
      - '127.0.0.1:${REDPANDA_SCHEMA_PORT}:8081'
      - '127.0.0.1:${REDPANDA_METRICS_PORT}:9644'

  redpanda-console:
    ports:
      - '127.0.0.1:${REDPANDA_CONSOLE_PORT}:8080'

  postgres:
    ports:
      - '127.0.0.1:${POSTGRES_PORT}:5432'

  clickhouse:
    ports:
      - '127.0.0.1:${CLICKHOUSE_HTTP_PORT}:8123'
      - '127.0.0.1:${CLICKHOUSE_NATIVE_PORT}:9000'

  jaeger:
    ports:
      - '127.0.0.1:${JAEGER_PORT}:16686'

  otel-collector:
    ports:
      - '127.0.0.1:${OTEL_GRPC_PORT}:4317'
      - '127.0.0.1:${OTEL_HTTP_PORT}:4318'

  api:
    ports:
      - '127.0.0.1:${API_PORT}:8000'

  web:
    ports:
      - '127.0.0.1:${WEB_PORT}:80'

  prometheus:
    ports:
      - '127.0.0.1:${PROMETHEUS_PORT}:9090'

  grafana:
    ports:
      - '127.0.0.1:${GRAFANA_PORT}:3000'
